-- MySQL Script generated by MySQL Workbench
-- seg 04 nov 2024 22:33:38
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Editora` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Livro` (
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `edicao` VARCHAR(45) NULL,
  `ano_pub` INT NULL,
  `cnpj` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_Livro_Editora1_idx` (`cnpj` ASC),
  CONSTRAINT `fk_Livro_Editora1`
    FOREIGN KEY (`cnpj`)
    REFERENCES `biblioteca`.`Editora` (`cnpj`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `biblioteca`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Autor` (
  `isbn` INT NOT NULL,
  `nomeAutor` VARCHAR(45) NOT NULL,
  INDEX `isbn_idx` (`isbn` ASC),
  PRIMARY KEY (`isbn`, `nomeAutor`),
  CONSTRAINT `isbn`
    FOREIGN KEY (`isbn`)
    REFERENCES `biblioteca`.`Livro` (`isbn`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Exemplar` (
  `idExemplar` INT NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `tipoEmprestimo` VARCHAR(45) NULL,
  `isbn` INT NOT NULL,
  PRIMARY KEY (`idExemplar`),
  INDEX `fk_Exemplar_Livro1_idx` (`isbn` ASC),
  CONSTRAINT `fk_Exemplar_Livro1`
    FOREIGN KEY (`isbn`)
    REFERENCES `biblioteca`.`Livro` (`isbn`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Usuario` (
  `numMatricula` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`numMatricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Fone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Fone` (
  `numMatricula` INT NOT NULL,
  `numFone` INT NOT NULL,
  PRIMARY KEY (`numMatricula`, `numFone`),
  INDEX `fk_Fone_Usuario1_idx` (`numMatricula` ASC),
  CONSTRAINT `fk_Fone_Usuario1`
    FOREIGN KEY (`numMatricula`)
    REFERENCES `biblioteca`.`Usuario` (`numMatricula`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Emprestimo` (
  `idExemplar` INT NOT NULL,
  `numMatricula` INT NOT NULL,
  `dataLimiteDev` INT NOT NULL,
  `dataEmp` INT NOT NULL,
  `dataRealDev` INT NULL,
  PRIMARY KEY (`idExemplar`, `numMatricula`),
  INDEX `fk_Exemplar_has_Usuario_Usuario1_idx` (`numMatricula` ASC),
  INDEX `fk_Exemplar_has_Usuario_Exemplar1_idx` (`idExemplar` ASC),
  CONSTRAINT `fk_Exemplar_has_Usuario_Exemplar1`
    FOREIGN KEY (`idExemplar`)
    REFERENCES `biblioteca`.`Exemplar` (`idExemplar`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exemplar_has_Usuario_Usuario1`
    FOREIGN KEY (`numMatricula`)
    REFERENCES `biblioteca`.`Usuario` (`numMatricula`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
